---
sidebar: sidebar 
permalink: trident-docker/multiple-instances-docker.html 
keywords: deploy, Trident, docker, trident for docker, managed plugin, trident instances, alias 
summary: Se necesitan varias instancias de Trident cuando se desea tener varias configuraciones de almacenamiento disponibles simultáneamente.  La clave para tener múltiples instancias es darles nombres diferentes usando la opción --alias con el complemento en contenedor, o la opción --volume-driver al instanciar Trident en el host. 
---
= Gestionar múltiples instancias de Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se necesitan varias instancias de Trident cuando se desea tener varias configuraciones de almacenamiento disponibles simultáneamente.  La clave para múltiples instancias es darles nombres diferentes usando el `--alias` opción con el plugin en contenedor, o `--volume-driver` opción al instanciar Trident en el host.



== Pasos para el plugin gestionado por Docker (versión 1.13/17.03 o posterior)

. Inicie la primera instancia especificando un alias y un archivo de configuración.
+
[source, console]
----
docker plugin install --grant-all-permissions --alias silver netapp/trident-plugin:21.07 config=silver.json
----
. Inicie la segunda instancia, especificando un alias y un archivo de configuración diferentes.
+
[source, console]
----
docker plugin install --grant-all-permissions --alias gold netapp/trident-plugin:21.07 config=gold.json
----
. Cree volúmenes especificando el alias como nombre del controlador.
+
Por ejemplo, en el caso del volumen de oro:

+
[source, console]
----
docker volume create -d gold --name ntapGold
----
+
Por ejemplo, para el volumen de plata:

+
[source, console]
----
docker volume create -d silver --name ntapSilver
----




== Pasos para la versión tradicional (versión 1.12 o anterior)

. Inicie el complemento con una configuración NFS utilizando un ID de controlador personalizado:
+
[source, console]
----
sudo trident --volume-driver=netapp-nas --config=/path/to/config-nfs.json
----
. Inicie el complemento con una configuración iSCSI utilizando un ID de controlador personalizado:
+
[source, console]
----
sudo trident --volume-driver=netapp-san --config=/path/to/config-iscsi.json
----
. Aprovisionar volúmenes de Docker para cada instancia del controlador:
+
Por ejemplo, para NFS:

+
[source, console]
----
docker volume create -d netapp-nas --name my_nfs_vol
----
+
Por ejemplo, para iSCSI:

+
[source, console]
----
docker volume create -d netapp-san --name my_iscsi_vol
----

