---
sidebar: sidebar 
permalink: trident-docker/prereqs-docker.html 
keywords: deploy, Trident, docker, trident for docker, nfs, iscsi, protcol, nfs protocol, iscsi protocol, configure host, host config, nvme/tcp, nvme 
summary: Debes instalar y configurar los requisitos previos del protocolo necesarios en tu host antes de poder implementar Trident. 
---
= Requisitos previos para la implementación
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debes instalar y configurar los requisitos previos del protocolo necesarios en tu host antes de poder implementar Trident.



== Verificar los requisitos

* Verifique que su implementación cumpla con todos los requisitos.link:../trident-get-started/requirements.html["requisitos"] .
* Verifique que tiene instalada una versión compatible de Docker.  Si tu versión de Docker está desactualizada, https://docs.docker.com/engine/install/["instalarlo o actualizarlo"^] .
+
[source, console]
----
docker --version
----
* Verifique que los requisitos previos del protocolo estén instalados y configurados en su host.




=== Herramientas NFS

Instala las herramientas NFS utilizando los comandos correspondientes a tu sistema operativo.

[role="tabbed-block"]
====
.RHEL 8+
--
[source, console]
----
sudo yum install -y nfs-utils
----
--
.Ubuntu
--
[source, console]
----
sudo apt-get install -y nfs-common
----
--
====

WARNING: Reinicie sus nodos de trabajo después de instalar las herramientas NFS para evitar fallos al conectar volúmenes a los contenedores.



=== herramientas iSCSI

Instale las herramientas iSCSI utilizando los comandos correspondientes a su sistema operativo.

[role="tabbed-block"]
====
.RHEL 8+
--
. Instale los siguientes paquetes del sistema:
+
[source, console]
----
sudo yum install -y lsscsi iscsi-initiator-utils sg3_utils device-mapper-multipath
----
. Compruebe que la versión de iscsi-initiator-utils sea la 6.2.0.874-2.el7 o posterior:
+
[source, console]
----
rpm -q iscsi-initiator-utils
----
. Configurar el escaneo en modo manual:
+
[source, console]
----
sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf
----
. Habilitar rutas múltiples:
+
[source, console]
----
sudo mpathconf --enable --with_multipathd y --find_multipaths n
----
+

NOTE: Asegurar `etc/multipath.conf` contiene `find_multipaths no` bajo `defaults` .

. Asegúrese de que `iscsid` y `multipathd` están en funcionamiento:
+
[source, console]
----
sudo systemctl enable --now iscsid multipathd
----
. Habilitar e iniciar `iscsi` :
+
[source, console]
----
sudo systemctl enable --now iscsi
----


--
.Ubuntu
--
. Instale los siguientes paquetes del sistema:
+
[source, console]
----
sudo apt-get install -y open-iscsi lsscsi sg3-utils multipath-tools scsitools
----
. Compruebe que la versión de open-iscsi sea 2.0.874-5ubuntu2.10 o posterior (para bionic) o 2.0.874-7.1ubuntu6.1 o posterior (para focal):
+
[source, console]
----
dpkg -l open-iscsi
----
. Configurar el escaneo en modo manual:
+
[source, console]
----
sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf
----
. Habilitar rutas múltiples:
+
[source, console]
----
sudo tee /etc/multipath.conf <<-EOF
defaults {
    user_friendly_names yes
    find_multipaths no
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart
----
+

NOTE: Asegurar `etc/multipath.conf` contiene `find_multipaths no` bajo `defaults` .

. Asegúrese de que `open-iscsi` y `multipath-tools` están habilitados y en funcionamiento:
+
[source, console]
----
sudo systemctl status multipath-tools
sudo systemctl enable --now open-iscsi.service
sudo systemctl status open-iscsi
----


--
====


== Herramientas NVMe

Instala las herramientas NVMe utilizando los comandos correspondientes a tu sistema operativo.

[NOTE]
====
* NVMe requiere RHEL 9 o posterior.
* Si la versión del kernel de su nodo de Kubernetes es demasiado antigua o si el paquete NVMe no está disponible para su versión del kernel, es posible que deba actualizar la versión del kernel de su nodo a una que incluya el paquete NVMe.


====
[role="tabbed-block"]
====
.RHEL 9
--
[source, console]
----
sudo yum install nvme-cli
sudo yum install linux-modules-extra-$(uname -r)
sudo modprobe nvme-tcp
----
--
.Ubuntu
--
[source, console]
----
sudo apt install nvme-cli
sudo apt -y install linux-modules-extra-$(uname -r)
sudo modprobe nvme-tcp
----
--
====


== Herramientas FC

Instala las herramientas FC utilizando los comandos correspondientes a tu sistema operativo.

* Cuando utilice nodos de trabajo que ejecuten RHEL/Red Hat Enterprise Linux CoreOS (RHCOS) con PV FC, especifique el `discard` mountOption en la StorageClass para realizar la recuperación de espacio en línea. Referirse a https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems["Documentación de Red Hat"^] .


[role="tabbed-block"]
====
.RHEL 8+
--
. Instale los siguientes paquetes del sistema:
+
[source, console]
----
sudo yum install -y lsscsi device-mapper-multipath
----
. Habilitar rutas múltiples:
+
[source, console]
----
sudo mpathconf --enable --with_multipathd y --find_multipaths n
----
+

NOTE: Asegurar `etc/multipath.conf` contiene `find_multipaths no` bajo `defaults` .

. Asegúrese de que `multipathd` está en funcionamiento:
+
[source, console]
----
sudo systemctl enable --now multipathd
----


--
.Ubuntu
--
. Instale los siguientes paquetes del sistema:
+
[source, console]
----
sudo apt-get install -y lsscsi sg3-utils multipath-tools scsitools
----
. Habilitar rutas múltiples:
+
[source, console]
----
sudo tee /etc/multipath.conf <<-EOF
defaults {
    user_friendly_names yes
    find_multipaths no
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart
----
+

NOTE: Asegurar `etc/multipath.conf` contiene `find_multipaths no` bajo `defaults` .

. Asegúrese de que `multipath-tools` está habilitado y en funcionamiento:
+
[source, console]
----
sudo systemctl status multipath-tools
----


--
====