---
sidebar: sidebar 
permalink: trident-docker/stor-config.html 
keywords: deploy, trident, docker, trident for docker, nfs, iscsi, protocol, nfs protocol, iscsi protocol, configure host, host config, storage config, options, variables, ontap, element, storage pool, cvs, cvs-performance, service type, service level, cloud volumes service, cloud volumes 
summary: Consulte las opciones de configuración disponibles para sus configuraciones de Trident . 
---
= Opciones de configuración de almacenamiento
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Consulte las opciones de configuración disponibles para sus configuraciones de Trident .



== Opciones de configuración global

Estas opciones de configuración se aplican a todas las configuraciones de Trident , independientemente de la plataforma de almacenamiento que se utilice.

[cols="3*"]
|===
| Opción | Descripción | Ejemplo 


| `version`  a| 
Número de versión del archivo de configuración
 a| 
`1`



| `storageDriverName`  a| 
Nombre del controlador de almacenamiento
 a| 
`ontap-nas`, `ontap-san` , `ontap-nas-economy` ,
`ontap-nas-flexgroup` , `solidfire-san`



| `storagePrefix`  a| 
Prefijo opcional para los nombres de los volúmenes.  Por defecto: `netappdvp_` .
 a| 
`staging_`



| `limitVolumeSize`  a| 
Restricción opcional en los tamaños de volumen.  Valor predeterminado: "" (no se aplica)
 a| 
`10g`

|===

TIP: No utilizar `storagePrefix` (incluido el valor predeterminado) para los backends de Element.  De forma predeterminada, el `solidfire-san` El controlador ignorará esta configuración y no utilizará un prefijo.  NetApp recomienda usar un tenantID específico para la asignación de volúmenes de Docker o usar los datos de atributos que se completan con la versión de Docker, la información del controlador y el nombre sin procesar de Docker en los casos en que se haya utilizado alguna manipulación de nombres.

Se ofrecen opciones predeterminadas para evitar tener que especificarlas en cada volumen que cree.  El `size` Esta opción está disponible para todos los tipos de controladores.  Consulte la sección de configuración de ONTAP para ver un ejemplo de cómo configurar el tamaño de volumen predeterminado.

[cols="3*"]
|===
| Opción | Descripción | Ejemplo 


| `size`  a| 
Tamaño predeterminado opcional para nuevos volúmenes.  Por defecto: `1G`
 a| 
`10G`

|===


== Configuración de ONTAP

Además de los valores de configuración global anteriores, al usar ONTAP, están disponibles las siguientes opciones de nivel superior.

[cols="3*"]
|===
| Opción | Descripción | Ejemplo 


| `managementLIF`  a| 
Dirección IP de la LIF de gestión de ONTAP .  Puede especificar un nombre de dominio completo (FQDN).
 a| 
`10.0.0.1`



| `dataLIF`  a| 
Dirección IP del protocolo LIF.

* Controladores NAS ONTAP *: NetApp recomienda especificar `dataLIF` .  Si no se proporcionan, Trident obtiene los dataLIF del SVM.  Puede especificar un nombre de dominio completo (FQDN) para usarlo en las operaciones de montaje NFS, lo que le permite crear un DNS round-robin para equilibrar la carga entre varios dataLIF.

* Controladores SAN ONTAP *: No especifique para iSCSI o FC.  Trident utilizalink:https://docs.netapp.com/us-en/ontap/san-admin/selective-lun-map-concept.html["Mapa selectivo de LUN de ONTAP"^] para descubrir los LIF iSCSI o FC necesarios para establecer una sesión de múltiples rutas.  Se genera una advertencia si `dataLIF` está definido explícitamente.
 a| 
`10.0.0.2`



| `svm`  a| 
Máquina virtual de almacenamiento a utilizar (obligatoria si la LIF de gestión es una LIF de clúster)
 a| 
`svm_nfs`



| `username`  a| 
Nombre de usuario para conectarse al dispositivo de almacenamiento
 a| 
`vsadmin`



| `password`  a| 
Contraseña para conectarse al dispositivo de almacenamiento
 a| 
`secret`



| `aggregate`  a| 
Agregado para aprovisionamiento (opcional; si se establece, debe asignarse a la SVM).  Para el `ontap-nas-flexgroup` conductor, esta opción se ignora.  Todos los agregados asignados al SVM se utilizan para aprovisionar un volumen FlexGroup .
 a| 
`aggr1`



| `limitAggregateUsage`  a| 
Opcional: el aprovisionamiento puede fallar si el uso supera este porcentaje.
 a| 
`75%`



| `nfsMountOptions`  a| 
Control preciso de las opciones de montaje NFS; el valor predeterminado es "-o nfsvers=3".  *Disponible solo para `ontap-nas` y `ontap-nas-economy` conductores*. https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf["Consulte aquí la información de configuración del host NFS."^] .
 a| 
`-o nfsvers=4`



| `igroupName`  a| 
Trident crea y gestiona por nodo `igroups` como `netappdvp` .

Este valor no se puede cambiar ni omitir.

*Disponible solo para `ontap-san` conductor*.
 a| 
`netappdvp`



| `limitVolumeSize`  a| 
Tamaño máximo de volumen solicitable.
 a| 
`300g`



| `qtreesPerFlexvol`  a| 
Número máximo de qtrees por FlexVol, debe estar en el rango [50, 300], el valor predeterminado es 200.

*Para el `ontap-nas-economy` controlador, esta opción permite personalizar el número máximo de qtrees por FlexVol*.
 a| 
`300`



 a| 
`sanType`
| *Compatible con `ontap-san` Solo el conductor.*  Utilice para seleccionar `iscsi` para iSCSI, `nvme` para NVMe/TCP o `fcp` para SCSI sobre Fibre Channel (FC). | `iscsi`si está en blanco 


| `limitVolumePoolSize` | *Compatible con `ontap-san-economy` y `ontap-san-economy` Solo conductores.*  Limita los tamaños de FlexVol en los controladores ONTAP ontap-nas-economy y ontap-SAN-economy.  a| 
`300g`

|===
Se ofrecen opciones predeterminadas para evitar tener que especificarlas en cada volumen que cree:

[cols="1,3,2"]
|===
| Opción | Descripción | Ejemplo 


| `spaceReserve`  a| 
Modo de reserva de espacio; `none` (con provisiones escasas) o `volume` (grueso)
 a| 
`none`



| `snapshotPolicy`  a| 
Política de instantáneas a utilizar; la predeterminada es `none`
 a| 
`none`



| `snapshotReserve`  a| 
Porcentaje de reserva de instantánea, el valor predeterminado es "" para aceptar el valor predeterminado de ONTAP
 a| 
`10`



| `splitOnClone`  a| 
Al crear un clon, se separa de su padre; por defecto, se utiliza el método `divide`. `false`
 a| 
`false`



| `encryption`  a| 
Habilita el cifrado de volumen de NetApp (NVE) en el nuevo volumen; el valor predeterminado es `false` .  Para utilizar esta opción, NVE debe estar licenciado y habilitado en el clúster.

Si NAE está habilitado en el backend, cualquier volumen aprovisionado en Trident tendrá NAE habilitado.

Para obtener más información, consulte:link:../trident-reco/security-reco.html["Cómo funciona Trident con NVE y NAE"] .
 a| 
verdadero



| `unixPermissions`  a| 
Opción NAS para volúmenes NFS aprovisionados, valor predeterminado `777`
 a| 
`777`



| `snapshotDir`  a| 
Opción NAS para acceder a `.snapshot` directorio.
 a| 
"verdadero" para NFSv4, "falso" para NFSv3



| `exportPolicy`  a| 
Opción NAS para la política de exportación NFS a utilizar, por defecto a `default`
 a| 
`default`



| `securityStyle`  a| 
Opción NAS para acceder al volumen NFS aprovisionado.

NFS admite `mixed` y `unix` Estilos de seguridad.  El valor predeterminado es `unix` .
 a| 
`unix`



| `fileSystemType`  a| 
Opción SAN para seleccionar el tipo de sistema de archivos, por defecto es `ext4`
 a| 
`xfs`



| `tieringPolicy`  a| 
La política de niveles a utilizar, por defecto es `none` .
 a| 
`none`

|===


=== Opciones de escala

El `ontap-nas` y `ontap-san` Los controladores crean un ONTAP FlexVol para cada volumen de Docker.  ONTAP admite hasta 1000 FlexVols por nodo de clúster, con un máximo de 12 000 volúmenes FlexVol por clúster. Si sus requisitos de volumen de Docker se ajustan a esa limitación, `ontap-nas` El controlador es la solución NAS preferida debido a las características adicionales que ofrece FlexVols, como instantáneas granulares de volumen Docker y clonación.

Si necesita más volúmenes de Docker de los que pueden admitir los límites de FlexVol , elija la opción `ontap-nas-economy` o el `ontap-san-economy` conductor.

El `ontap-nas-economy` El controlador crea volúmenes Docker como Qtrees de ONTAP dentro de un grupo de volúmenes FlexVol gestionados automáticamente.  Los Qtrees ofrecen una escalabilidad mucho mayor, hasta 100.000 por nodo de clúster y 2.400.000 por clúster, a costa de algunas características.  El `ontap-nas-economy` El controlador no admite instantáneas granulares de volumen de Docker ni clonación.


NOTE: El `ontap-nas-economy` Actualmente, el controlador no es compatible con Docker Swarm, ya que Docker Swarm no orquesta la creación de volúmenes en múltiples nodos.

El `ontap-san-economy` El controlador crea volúmenes Docker como LUN ONTAP dentro de un grupo compartido de volúmenes FlexVol gestionados automáticamente.  De esta forma, cada FlexVol no se limita a un solo LUN y ofrece una mejor escalabilidad para las cargas de trabajo SAN.  Dependiendo de la matriz de almacenamiento, ONTAP admite hasta 16384 LUN por clúster.  Debido a que los volúmenes subyacentes son LUN, este controlador admite instantáneas granulares de volumen de Docker y clonación.

Elige el `ontap-nas-flexgroup` Controlador para aumentar el paralelismo en un único volumen que puede crecer hasta el rango de petabytes con miles de millones de archivos.  Algunos casos de uso ideales para FlexGroups incluyen IA/ML/DL, big data y análisis, compilaciones de software, streaming, repositorios de archivos, etc.  Trident utiliza todos los agregados asignados a una SVM al aprovisionar un volumen FlexGroup .  La compatibilidad con FlexGroup en Trident también tiene las siguientes consideraciones:

* Requiere ONTAP versión 9.2 o superior.
* Al momento de escribir este artículo, FlexGroups solo admite NFS v3.
* Se recomienda habilitar los identificadores NFSv3 de 64 bits para la SVM.
* El tamaño mínimo recomendado para el miembro/volumen de FlexGroup es 100 GiB.
* La clonación no es compatible con volúmenes FlexGroup .


Para obtener información sobre FlexGroups y las cargas de trabajo adecuadas para FlexGroups, consulte la https://www.netapp.com/pdf.html?item=/media/12385-tr4571pdf.pdf["Guía de implementación y mejores prácticas de NetApp FlexGroup volume"^] .

Para obtener funciones avanzadas y gran escala en el mismo entorno, puede ejecutar varias instancias del complemento Docker Volume, una de las cuales utilizará `ontap-nas` y otro usando `ontap-nas-economy` .



=== Rol ONTAP personalizado para Trident

Puede crear un rol de clúster ONTAP con privilegios mínimos para que no tenga que usar el rol de administrador de ONTAP para realizar operaciones en Trident.  Cuando incluyes el nombre de usuario en una configuración de backend de Trident , Trident utiliza el rol de clúster ONTAP que creaste para realizar las operaciones.

Referirse alink:https://github.com/NetApp/trident/tree/master/contrib/ontap/trident_role["Generador de roles personalizados de Trident"] Para obtener más información sobre la creación de roles personalizados de Trident .

[role="tabbed-block"]
====
.Uso de la CLI de ONTAP
--
. Crea un nuevo rol utilizando el siguiente comando:
+
`security login role create <role_name\> -cmddirname "command" -access all -vserver <svm_name\>`

. Crea un nombre de usuario para el usuario de Trident :
+
`security login create -username <user_name\> -application ontapi -authmethod password -role <name_of_role_in_step_1\> -vserver <svm_name\> -comment "user_description"`
`security login create -username <user_name\> -application http -authmethod password -role <name_of_role_in_step_1\> -vserver <svm_name\> -comment "user_description"`

. Asigna el rol al usuario:
+
`security login modify username <user_name\> -vserver <svm_name\> -role <role_name\> -application ontapi -application console -authmethod <password\>`



--
.Usando el Administrador del sistema
--
Realice los siguientes pasos en ONTAP System Manager:

. *Crea un rol personalizado*:
+
.. Para crear un rol personalizado a nivel de clúster, seleccione *Clúster > Configuración*.
+
(O) Para crear un rol personalizado a nivel de SVM, seleccione *Almacenamiento > Máquinas virtuales de almacenamiento > `required SVM` > Configuración > Usuarios y roles*.

.. Seleccione el icono de flecha (*->*) junto a *Usuarios y roles*.
.. Seleccione ***Agregar* en *Roles*.
.. Define las reglas para el rol y haz clic en *Guardar*.


. *Asigna el rol al usuario de Trident *: + Realiza los siguientes pasos en la página *Usuarios y roles*:
+
.. Seleccione el icono Agregar **+* debajo de *Usuarios*.
.. Seleccione el nombre de usuario requerido y seleccione un rol en el menú desplegable para *Rol*.
.. Haga clic en *Guardar*.




--
====
Para obtener más información, consulte las siguientes páginas:

* link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/FAQ__Custom_roles_for_administration_of_ONTAP["Roles personalizados para la administración de ONTAP"^]olink:https://docs.netapp.com/us-en/ontap/authentication/define-custom-roles-task.html["Definir roles personalizados"^]
* link:https://docs.netapp.com/us-en/ontap-automation/rest/rbac_roles_users.html#rest-api["Trabajar con roles y usuarios"^]




=== Ejemplos de archivos de configuración de ONTAP

.Ejemplo de NFS para el controlador <code>ontap-nas</code>
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.2",
  "svm": "svm_nfs",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1",
  "defaults": {
    "size": "10G",
    "spaceReserve": "none",
    "exportPolicy": "default"
  }
}
----
====
.Ejemplo de NFS para el controlador <code>ontap-nas-flexgroup</code>
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas-flexgroup",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.2",
  "svm": "svm_nfs",
  "username": "vsadmin",
  "password": "password",
  "defaults": {
    "size": "100G",
    "spaceReserve": "none",
    "exportPolicy": "default"
  }
}
----
====
.Ejemplo de NFS para el controlador <code>ontap-nas-economy</code>
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas-economy",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.2",
  "svm": "svm_nfs",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1"
}
----
====
.Ejemplo de iSCSI para el controlador <code>ontap-san</code>
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.3",
  "svm": "svm_iscsi",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1",
  "igroupName": "netappdvp"
}
----
====
.Ejemplo de NFS para el controlador <code>ontap-san-economy</code>
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-san-economy",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.3",
  "svm": "svm_iscsi_eco",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1",
  "igroupName": "netappdvp"
}
----
====
.Ejemplo NVMe/TCP para el controlador <code>ontap-san</code>
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "backendName": "NVMeBackend",
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "svm": "svm_nvme",
  "username": "vsadmin",
  "password": "password",
  "sanType": "nvme",
  "useREST": true
}
----
====
.Ejemplo de SCSI sobre FC para el controlador <code>ontap-san</code>
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "backendName": "ontap-san-backend",
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "sanType": "fcp",
  "svm": "trident_svm",
  "username": "vsadmin",
  "password": "password",
  "useREST": true
}
----
====


== Configuración del software Element

Además de los valores de configuración global, al usar el software Element (NetApp HCI/ SolidFire), están disponibles estas opciones.

[cols="3*"]
|===
| Opción | Descripción | Ejemplo 


| `Endpoint`  a| 
https://<login>:<password>@<mvip>/json-rpc/<element-version>
 a| 
https://admin:admin@192.168.160.3/json-rpc/8.0



| `SVIP`  a| 
Dirección IP y puerto iSCSI
 a| 
10.0.0.7:3260



| `TenantName`  a| 
Tenent de SolidFireF a utilizar (se creará si no se encuentra)
 a| 
`docker`



| `InitiatorIFace`  a| 
Especifique la interfaz al restringir el tráfico iSCSI a una interfaz no predeterminada.
 a| 
`default`



| `Types`  a| 
Especificaciones de QoS
 a| 
Vea el ejemplo a continuación.



| `LegacyNamePrefix`  a| 
Prefijo para instalaciones Trident actualizadas.  Si utilizó una versión de Trident anterior a la 1.3.2 y realiza una actualización con volúmenes existentes, deberá establecer este valor para acceder a sus volúmenes antiguos que se asignaron mediante el método nombre de volumen.
 a| 
`netappdvp-`

|===
El `solidfire-san` El controlador no es compatible con Docker Swarm.



=== Archivo de configuración de software de ejemplo de Element

[source, json]
----
{
  "version": 1,
  "storageDriverName": "solidfire-san",
  "Endpoint": "https://admin:admin@192.168.160.3/json-rpc/8.0",
  "SVIP": "10.0.0.7:3260",
  "TenantName": "docker",
  "InitiatorIFace": "default",
  "Types": [
    {
      "Type": "Bronze",
      "Qos": {
        "minIOPS": 1000,
        "maxIOPS": 2000,
        "burstIOPS": 4000
      }
    },
    {
      "Type": "Silver",
      "Qos": {
        "minIOPS": 4000,
        "maxIOPS": 6000,
        "burstIOPS": 8000
      }
    },
    {
      "Type": "Gold",
      "Qos": {
        "minIOPS": 6000,
        "maxIOPS": 8000,
        "burstIOPS": 10000
      }
    }
  ]
}
----