---
sidebar: sidebar 
permalink: trident-docker/upgrade-uninstall-docker.html 
keywords: uninstall, Trident, trident for docker, docker, upgrade trident for docker 
summary: 'Puede actualizar Trident para Docker de forma segura sin que ello afecte a los volúmenes que estén en uso.  Durante el proceso de actualización habrá un breve período en el que `docker volume` Los comandos dirigidos al complemento no tendrán éxito y las aplicaciones no podrán montar volúmenes hasta que el complemento vuelva a estar en funcionamiento.  En la mayoría de los casos, esto es cuestión de segundos.' 
---
= Actualizar o desinstalar Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede actualizar Trident para Docker de forma segura sin que ello afecte a los volúmenes que estén en uso.  Durante el proceso de actualización habrá un breve período en el que `docker volume` Los comandos dirigidos al complemento no tendrán éxito y las aplicaciones no podrán montar volúmenes hasta que el complemento vuelva a estar en funcionamiento.  En la mayoría de los casos, esto es cuestión de segundos.



== Mejora

Siga los pasos a continuación para actualizar Trident para Docker.

.Pasos
. Enumere los volúmenes existentes:
+
[listing]
----
docker volume ls
DRIVER              VOLUME NAME
netapp:latest       my_volume
----
. Desactivar el plugin:
+
[listing]
----
docker plugin disable -f netapp:latest
docker plugin ls
ID                  NAME                DESCRIPTION                          ENABLED
7067f39a5df5        netapp:latest       nDVP - NetApp Docker Volume Plugin   false
----
. Actualizar el plugin:
+
[listing]
----
docker plugin upgrade --skip-remote-check --grant-all-permissions netapp:latest netapp/trident-plugin:21.07
----
+

NOTE: La versión 18.01 de Trident reemplaza a nDVP.  Deberías actualizar directamente desde el `netapp/ndvp-plugin` imagen a la `netapp/trident-plugin` imagen.

. Habilitar el plugin:
+
[listing]
----
docker plugin enable netapp:latest
----
. Verifique que el plugin esté habilitado:
+
[listing]
----
docker plugin ls
ID                  NAME                DESCRIPTION                             ENABLED
7067f39a5df5        netapp:latest       Trident - NetApp Docker Volume Plugin   true
----
. Verifique que los volúmenes sean visibles:
+
[listing]
----
docker volume ls
DRIVER              VOLUME NAME
netapp:latest       my_volume
----



IMPORTANT: Si está actualizando desde una versión antigua de Trident (anterior a la 20.10) a Trident 20.10 o posterior, podría encontrarse con un error.  Para obtener más información, consultelink:known-issues-docker.html["Problemas conocidos"^] .  Si se produce este error, primero debe desactivar el plugin, luego eliminarlo y, a continuación, instalar la versión de Trident necesaria pasando un parámetro de configuración adicional: `docker plugin install netapp/trident-plugin:20.10 --alias netapp --grant-all-permissions config=config.json`



== Desinstalar

Siga los pasos que se indican a continuación para desinstalar Trident para Docker.

.Pasos
. Elimine cualquier volumen que haya creado el plugin.
. Desactivar el plugin:
+
[listing]
----
docker plugin disable netapp:latest
docker plugin ls
ID                  NAME                DESCRIPTION                          ENABLED
7067f39a5df5        netapp:latest       nDVP - NetApp Docker Volume Plugin   false
----
. Eliminar el plugin:
+
[listing]
----
docker plugin rm netapp:latest
----

