---
sidebar: sidebar 
permalink: trident-docker/volumes-docker.html 
keywords: create volumes, Trident, trident for docker, docker, docker volume 
summary: 'Para crear volúmenes, utilice el estándar `docker volume` comandos con el nombre del controlador Trident especificado cuando sea necesario.' 
---
= Trabajar con volúmenes
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede crear, clonar y eliminar volúmenes fácilmente utilizando el estándar. `docker volume` comandos con el nombre del controlador Trident especificado cuando sea necesario.



== Crear un volumen

* Crea un volumen con una unidad utilizando el nombre predeterminado:
+
[source, console]
----
docker volume create -d netapp --name firstVolume
----
* Crear un volumen con una instancia específica de Trident :
+
[source, console]
----
docker volume create -d ntap_bronze --name bronzeVolume
----
+

NOTE: Si no especifica ningunolink:volume-driver-options.html["opciones"^] Se utilizan los valores predeterminados del controlador.

* Anule el tamaño de volumen predeterminado. Consulte el siguiente ejemplo para crear un volumen de 20 GiB con un controlador:
+
[source, console]
----
docker volume create -d netapp --name my_vol --opt size=20G
----
+

TIP: Los tamaños de volumen se expresan como cadenas que contienen un valor entero con unidades opcionales (ejemplo: 10G, 20GB, 3TiB).  Si no se especifican unidades, el valor predeterminado es G. Las unidades de tamaño se pueden expresar como potencias de 2 (B, KiB, MiB, GiB, TiB) o potencias de 10 (B, KB, MB, GB, TB).  Las unidades abreviadas utilizan potencias de 2 (G = GiB, T = TiB, …).





== Eliminar un volumen

* Elimine el volumen como cualquier otro volumen de Docker:
+
[source, console]
----
docker volume rm firstVolume
----
+

IMPORTANT: Al usar el `solidfire-san` El controlador, en el ejemplo anterior, elimina y purga el volumen.



Siga los pasos a continuación para actualizar Trident para Docker.



== Clonar un volumen

Al usar el `ontap-nas` , `ontap-san` , `solidfire-san` , y `gcp-cvs storage drivers` Trident puede clonar volúmenes.  Al usar el `ontap-nas-flexgroup` o `ontap-nas-economy` controladores, la clonación no es compatible.  La creación de un nuevo volumen a partir de un volumen existente dará como resultado la creación de una nueva instantánea.

* Inspeccione el volumen para enumerar las instantáneas:
+
[source, console]
----
docker volume inspect <volume_name>
----
* Crear un nuevo volumen a partir de un volumen existente.  Esto dará como resultado la creación de una nueva instantánea:
+
[source, console]
----
docker volume create -d <driver_name> --name <new_name> -o from=<source_docker_volume>
----
* Crea un nuevo volumen a partir de una instantánea existente en un volumen.  Esto no creará una nueva instantánea:
+
[source, console]
----
docker volume create -d <driver_name> --name <new_name> -o from=<source_docker_volume> -o fromSnapshot=<source_snap_name>
----




=== Ejemplo

[source, console]
----
docker volume inspect firstVolume

[
  {
    "Driver": "ontap-nas",
    "Labels": null,
    "Mountpoint": "/var/lib/docker-volumes/ontap-nas/netappdvp_firstVolume",
    "Name": "firstVolume",
    "Options": {},
    "Scope": "global",
    "Status": {
      "Snapshots": [
        {
          "Created": "2017-02-10T19:05:00Z",
          "Name": "hourly.2017-02-10_1505"
        }
      ]
    }
  }
]

docker volume create -d ontap-nas --name clonedVolume -o from=firstVolume
clonedVolume

docker volume rm clonedVolume
docker volume create -d ontap-nas --name volFromSnap -o from=firstVolume -o fromSnapshot=hourly.2017-02-10_1505
volFromSnap

docker volume rm volFromSnap
----


== Acceso a volúmenes creados externamente

Los contenedores que utilizan Trident solo pueden acceder a dispositivos de bloque creados externamente (o sus clones) si no tienen particiones y si su sistema de archivos es compatible con Trident (por ejemplo: un `ext4` -formateado `/dev/sdc1` no será accesible a través de Trident).
