---
sidebar: sidebar 
permalink: trident-use/anf.html 
keywords: trident backend, azure netapp files, smb volumes, smb, windows, drivers, access modes, rwo, rwx, rwp, rwop, file system, aks, managed identities, azure 
summary: 'Puede configurar Azure NetApp Files como backend para Trident.  Puede conectar volúmenes NFS y SMB utilizando un backend de Azure NetApp Files .  Trident también admite la administración de credenciales mediante identidades administradas para clústeres de Azure Kubernetes Services (AKS).' 
---
= Configurar un backend de Azure NetApp Files
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar Azure NetApp Files como backend para Trident.  Puede conectar volúmenes NFS y SMB utilizando un backend de Azure NetApp Files .  Trident también admite la administración de credenciales mediante identidades administradas para clústeres de Azure Kubernetes Services (AKS).



== Detalles del controlador de Azure NetApp Files

Trident proporciona los siguientes controladores de almacenamiento de Azure NetApp Files para comunicarse con el clúster.  Los modos de acceso compatibles son: _ReadWriteOnce_ (RWO), _ReadOnlyMany_ (ROX), _ReadWriteMany_ (RWX), _ReadWriteOncePod_ (RWOP).

[cols="2, 1, 1, 2, 2"]
|===
| Conductor | Protocolo | modo de volumen | Modos de acceso compatibles | Sistemas de archivos compatibles 


| `azure-netapp-files`  a| 
NFS SMB
 a| 
Sistema de archivos
 a| 
RWO, ROX, RWX, RWOP
 a| 
`nfs`, `smb`

|===


=== Consideraciones

* El servicio Azure NetApp Files no admite volúmenes inferiores a 50 GiB.  Trident crea automáticamente volúmenes de 50 GiB si se solicita un volumen más pequeño.
* Trident solo admite volúmenes SMB montados en pods que se ejecutan en nodos Windows.




== Identidades administradas para AKS

Trident apoyalink:https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview["identidades gestionadas"^] para clústeres de Azure Kubernetes Services.  Para aprovechar la gestión simplificada de credenciales que ofrecen las identidades gestionadas, debe tener:

* Un clúster de Kubernetes implementado mediante AKS
* Identidades administradas configuradas en el clúster de Kubernetes de AKS
* Trident instalado que incluye el `cloudProvider` para especificar `"Azure"` .
+
[role="tabbed-block"]
====
.Operador de Trident
--
Para instalar Trident usando el operador Trident , edite `tridentorchestrator_cr.yaml` para establecer `cloudProvider` a `"Azure"` . Por ejemplo:

[source, yaml]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  imagePullPolicy: IfNotPresent
  cloudProvider: "Azure"
----
--
.Timón
--
El siguiente ejemplo instala conjuntos Trident `cloudProvider` a Azure usando la variable de entorno `$CP` :

[listing]
----
helm install trident trident-operator-100.2506.0.tgz --create-namespace --namespace <trident-namespace> --set cloudProvider=$CP
----
--
.<code>tridentctl</code>
--
El siguiente ejemplo instala Trident y configura `cloudProvider` bandera a `Azure` :

[listing]
----
tridentctl install --cloud-provider="Azure" -n trident
----
--
====




== Identidad en la nube para AKS

La identidad en la nube permite que los pods de Kubernetes accedan a los recursos de Azure autenticándose como una identidad de carga de trabajo en lugar de proporcionar credenciales explícitas de Azure.

Para aprovechar la identidad en la nube en Azure, debe tener:

* Un clúster de Kubernetes implementado mediante AKS
* La identidad de la carga de trabajo y el emisor OIDC están configurados en el clúster de Kubernetes de AKS.
* Trident instalado que incluye el `cloudProvider` para especificar `"Azure"` y `cloudIdentity` especificar la identidad de la carga de trabajo
+
[role="tabbed-block"]
====
.Operador de Trident
--
Para instalar Trident usando el operador Trident , edite `tridentorchestrator_cr.yaml` para establecer `cloudProvider` a `"Azure"` y establecer `cloudIdentity` a `azure.workload.identity/client-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx` .

Por ejemplo:

[source, yaml]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  imagePullPolicy: IfNotPresent
  cloudProvider: "Azure"
  cloudIdentity: 'azure.workload.identity/client-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx' # Edit
----
--
.Timón
--
Establezca los valores para las marcas *cloud-provider (CP)* y *cloud-identity (CI)* utilizando las siguientes variables de entorno:

`export CP="Azure"`
`export CI="'azure.workload.identity/client-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx'"`

El siguiente ejemplo instala Trident y lo configura. `cloudProvider` a Azure usando la variable de entorno `$CP` y establece el `cloudIdentity` utilizando la variable de entorno `$CI` :

[listing]
----
helm install trident trident-operator-100.6.0.tgz --set cloudProvider=$CP --set cloudIdentity="$CI"
----
--
.<code>tridentctl</code>
--
Configure los valores para las marcas *proveedor de nube* e *identidad de nube* utilizando las siguientes variables de entorno:

`export CP="Azure"`
`export CI="azure.workload.identity/client-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx"`

El siguiente ejemplo instala Trident y configura `cloud-provider` bandera a `$CP` , y `cloud-identity` a `$CI` :

[listing]
----
tridentctl install --cloud-provider=$CP --cloud-identity="$CI" -n trident
----
--
====

