---
sidebar: sidebar 
permalink: trident-use/backend_ops_kubectl.html 
keywords: backends, storage system, anf, cvs for aws, cvs for gcp, element, hci, solidfire, ontap, aff, fas, ontap select, configure backends, kubectl, create backends, delete backends, update backends, view backends 
summary: 'Aprenda cómo realizar operaciones de administración de backend utilizando `kubectl` .' 
---
= Realizar la gestión del backend con kubectl
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Aprenda cómo realizar operaciones de administración de backend utilizando `kubectl` .



== Eliminar un backend

Al eliminar un `TridentBackendConfig` , le indicas a Trident que elimine/conserve los backends (según `deletionPolicy` ).  Para eliminar un backend, asegúrese de que `deletionPolicy` está configurado para eliminar.  Para eliminar solo el `TridentBackendConfig` , asegúrese de que `deletionPolicy` está previsto que se mantenga.  Esto garantiza que el backend siga presente y pueda gestionarse mediante `tridentctl` .

Ejecute el siguiente comando:

[listing]
----
kubectl delete tbc <tbc-name> -n trident
----
Trident no elimina los secretos de Kubernetes que estaban en uso por `TridentBackendConfig` .  El usuario de Kubernetes es responsable de la limpieza de secretos.  Hay que tener cuidado al borrar secretos.  Solo debes eliminar los secretos si los backends no los están utilizando.



== Ver los backends existentes

Ejecute el siguiente comando:

[listing]
----
kubectl get tbc -n trident
----
También puedes correr `tridentctl get backend -n trident` o `tridentctl get backend -o yaml -n trident` para obtener una lista de todos los backends existentes.  Esta lista también incluirá backends que fueron creados con `tridentctl` .



== Actualizar un backend

Existen múltiples razones para actualizar un backend:

* Las credenciales del sistema de almacenamiento han cambiado.  Para actualizar las credenciales, el secreto de Kubernetes que se utiliza en el `TridentBackendConfig` El objeto debe actualizarse.  Trident actualizará automáticamente el sistema backend con las últimas credenciales proporcionadas.  Ejecute el siguiente comando para actualizar el secreto de Kubernetes:
+
[listing]
----
kubectl apply -f <updated-secret-file.yaml> -n trident
----
* Es necesario actualizar los parámetros (como el nombre de la SVM de ONTAP que se está utilizando).
+
** Puedes actualizar `TridentBackendConfig` objetos directamente a través de Kubernetes usando el siguiente comando:
+
[listing]
----
kubectl apply -f <updated-backend-file.yaml>
----
** Alternativamente, puede realizar cambios en el sistema existente. `TridentBackendConfig` CR usando el siguiente comando:
+
[listing]
----
kubectl edit tbc <tbc-name> -n trident
----




[NOTE]
====
* Si falla una actualización del backend, este permanecerá en su última configuración conocida.  Puedes ver los registros para determinar la causa ejecutando `kubectl get tbc <tbc-name> -o yaml -n trident` o `kubectl describe tbc <tbc-name> -n trident` .
* Después de identificar y corregir el problema con el archivo de configuración, puede volver a ejecutar el comando de actualización.


====