---
sidebar: sidebar 
permalink: trident-use/gcnv.html 
keywords: trident backend, google cloud netapp volumes, nfs volumes, nfs, drivers, access modes, rwo, rwx, rwp, rwop, file system, gke, cloud identity, google cloud 
summary:  
---
= Configurar un backend de Google Cloud NetApp Volumes
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ahora puedes configurar Google Cloud NetApp Volumes como backend para Trident.  Puedes conectar volúmenes NFS y SMB utilizando un backend de Google Cloud NetApp Volumes .



== Detalles del controlador de Google Cloud NetApp Volumes

Trident proporciona el `google-cloud-netapp-volumes` controlador para comunicarse con el clúster.  Los modos de acceso compatibles son: _ReadWriteOnce_ (RWO), _ReadOnlyMany_ (ROX), _ReadWriteMany_ (RWX), _ReadWriteOncePod_ (RWOP).

[cols="2, 1, 1, 2, 2"]
|===
| Conductor | Protocolo | modo de volumen | Modos de acceso compatibles | Sistemas de archivos compatibles 


| `google-cloud-netapp-volumes`  a| 
NFS SMB
 a| 
Sistema de archivos
 a| 
RWO, ROX, RWX, RWOP
 a| 
`nfs`, `smb`

|===


== Identidad en la nube para GKE

La identidad en la nube permite que los pods de Kubernetes accedan a los recursos de Google Cloud autenticándose como una identidad de carga de trabajo en lugar de proporcionar credenciales explícitas de Google Cloud.

Para aprovechar la identidad en la nube de Google Cloud, debes tener:

* Un clúster de Kubernetes desplegado utilizando GKE.
* La identidad de la carga de trabajo está configurada en el clúster de GKE y el servidor de metadatos de GKE está configurado en los grupos de nodos.
* Una cuenta de servicio de GCP con el rol de administrador de Google Cloud NetApp Volumes (roles/netapp.admin) o un rol personalizado.
* Trident instalado incluye cloudProvider para especificar "GCP" y cloudIdentity para especificar la nueva cuenta de servicio de GCP.  A continuación se muestra un ejemplo.
+
[role="tabbed-block"]
====
.Operador de Trident
--
Para instalar Trident usando el operador Trident , edite `tridentorchestrator_cr.yaml` para establecer `cloudProvider` a `"GCP"` y establecer `cloudIdentity` a `iam.gke.io/gcp-service-account: \cloudvolumes-admin-sa@mygcpproject.iam.gserviceaccount.com` .

Por ejemplo:

[source, yaml]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  imagePullPolicy: IfNotPresent
  cloudProvider: "GCP"
  cloudIdentity: 'iam.gke.io/gcp-service-account: cloudvolumes-admin-sa@mygcpproject.iam.gserviceaccount.com'
----
--
.Timón
--
Establezca los valores para las marcas *cloud-provider (CP)* y *cloud-identity (CI)* utilizando las siguientes variables de entorno:

`export CP="GCP"`
`export ANNOTATION="'iam.gke.io/gcp-service-account: \cloudvolumes-admin-sa@mygcpproject.iam.gserviceaccount.com'"`

El siguiente ejemplo instala Trident y lo configura. `cloudProvider` a GCP utilizando la variable de entorno `$CP` y establece el `cloudIdentity` utilizando la variable de entorno `$ANNOTATION` :

[listing]
----
helm install trident trident-operator-100.6.0.tgz --set cloudProvider=$CP --set cloudIdentity="$ANNOTATION"
----
--
.<code>tridentctl</code>
--
Configure los valores para las marcas *proveedor de nube* e *identidad de nube* utilizando las siguientes variables de entorno:

`export CP="GCP"`
`export ANNOTATION="'iam.gke.io/gcp-service-account: \cloudvolumes-admin-sa@mygcpproject.iam.gserviceaccount.com'"`

El siguiente ejemplo instala Trident y configura `cloud-provider` bandera a `$CP` , y `cloud-identity` a `$ANNOTATION` :

[listing]
----
tridentctl install --cloud-provider=$CP --cloud-identity="$ANNOTATION" -n trident
----
--
====

