---
sidebar: sidebar 
permalink: trident-use/vol-custom-name.html 
keywords: volumes, volume name, custom volume name, on-demand volume snapshots, expand volumes, iscsci volumes, nfs volumes, expand, expansion, 
summary: 'Trident permite asignar nombres y etiquetas significativas a los volúmenes creados para facilitar su identificación, monitorización, gestión y asignación a los recursos de Kubernetes (PVC) correspondientes.' 
---
= Personaliza los nombres y etiquetas de los volúmenes.
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Con Trident, puedes asignar nombres y etiquetas descriptivos a los volúmenes que crees.  Esto te ayuda a identificar y asignar fácilmente los volúmenes a sus respectivos recursos de Kubernetes (PVC).  También puede definir plantillas a nivel de backend para crear nombres de volumen personalizados y etiquetas personalizadas; cualquier volumen que cree, importe o clone se ajustará a las plantillas.



== Antes de empezar

Compatibilidad con nombres y etiquetas de volumen personalizables:

. Operaciones de creación, importación y clonación de volúmenes.
. En el caso del controlador ontap-nas-economy, solo el nombre del volumen Qtree cumple con la plantilla de nombre.
. En el caso del controlador ontap-san-economy, solo el nombre del LUN cumple con la plantilla de nombre.




== Limitaciones

. Los nombres de volumen personalizables solo son compatibles con los controladores ONTAP locales.
. Los nombres de volumen personalizables no se aplican a los volúmenes existentes.




== Comportamientos clave de los nombres de volumen personalizables

. Si se produce un fallo debido a una sintaxis no válida en una plantilla de nombre, falla la creación del backend.  Sin embargo, si falla la aplicación de la plantilla, el volumen se nombrará de acuerdo con la convención de nomenclatura existente.
. El prefijo de almacenamiento no es aplicable cuando un volumen se nombra utilizando una plantilla de nombre de la configuración del backend.  Se puede añadir directamente a la plantilla cualquier valor de prefijo deseado.




== Ejemplos de configuración de backend con plantilla de nombre y etiquetas

Se pueden definir plantillas de nombres personalizadas a nivel de raíz y/o de grupo.

.Ejemplo de nivel raíz
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas",
  "backendName": "ontap-nfs-backend",
  "managementLIF": "<ip address>",
  "svm": "svm0",
  "username": "<admin>",
  "password": "<password>",
  "defaults": {
    "nameTemplate": "{{.volume.Name}}_{{.labels.cluster}}_{{.volume.Namespace}}_{{.volume.RequestName}}"
  },
  "labels": {
    "cluster": "ClusterA",
    "PVC": "{{.volume.Namespace}}_{{.volume.RequestName}}"
  }
}
----
.Ejemplo de nivel de piscina
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas",
  "backendName": "ontap-nfs-backend",
  "managementLIF": "<ip address>",
  "svm": "svm0",
  "username": "<admin>",
  "password": "<password>",
  "useREST": true,
  "storage": [
    {
      "labels": {
        "labelname": "label1",
        "name": "{{ .volume.Name }}"
      },
      "defaults": {
        "nameTemplate": "pool01_{{ .volume.Name }}_{{ .labels.cluster }}_{{ .volume.Namespace }}_{{ .volume.RequestName }}"
      }
    },
    {
      "labels": {
        "cluster": "label2",
        "name": "{{ .volume.Name }}"
      },
      "defaults": {
        "nameTemplate": "pool02_{{ .volume.Name }}_{{ .labels.cluster }}_{{ .volume.Namespace }}_{{ .volume.RequestName }}"
      }
    }
  ]
}
----


== Ejemplos de plantillas de nombres

*Ejemplo 1*:

[listing]
----
"nameTemplate": "{{ .config.StoragePrefix }}_{{ .volume.Name }}_{{ .config.BackendName }}"
----
*Ejemplo 2*:

[listing]
----
"nameTemplate": "pool_{{ .config.StoragePrefix }}_{{ .volume.Name }}_{{ slice .volume.RequestName 1 5 }}""
----


== Puntos a considerar

. En el caso de importaciones de volúmenes, las etiquetas se actualizan solo si el volumen existente tiene etiquetas en un formato específico.  Por ejemplo: `{"provisioning":{"Cluster":"ClusterA", "PVC": "pvcname"}}` .
. En el caso de importaciones de volúmenes gestionados, el nombre del volumen sigue la plantilla de nombre definida en el nivel raíz de la definición del backend.
. Trident no admite el uso de un operador de segmentación con el prefijo de almacenamiento.
. Si las plantillas no generan nombres de volumen únicos, Trident añadirá algunos caracteres aleatorios para crear nombres de volumen únicos.
. Si el nombre personalizado de un volumen NAS economy supera los 64 caracteres, Trident nombrará los volúmenes según la convención de nomenclatura existente.  Para todos los demás controladores ONTAP , si el nombre del volumen excede el límite de nombres, el proceso de creación del volumen falla.

