---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-helm.html 
keywords: deploy, Trident, operator, helm, helm chart, configuration, values, standard, registry 
summary: Puedes desplegar el operador Trident e instalar Trident usando Helm.  Este proceso se aplica a las instalaciones en las que las imágenes de contenedor requeridas por Trident no están almacenadas en un registro privado. 
---
= Desplegar el operador Trident usando Helm (modo estándar)
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes desplegar el operador Trident e instalar Trident usando Helm.  Este proceso se aplica a las instalaciones en las que las imágenes de contenedor requeridas por Trident no están almacenadas en un registro privado.  Si dispone de un registro de imágenes privado, utilice ellink:kubernetes-deploy-helm-mirror.html["proceso para el despliegue sin conexión"] .



== Información crítica sobre Trident 25.06

*Debe leer la siguiente información crítica sobre Trident.*

.<strong>Información crítica sobre Trident</strong>
[%collapsible%open]
====
[]
=====
* Kubernetes 1.34 ahora es compatible con Trident. Actualice Trident antes de actualizar Kubernetes.
* Trident impone estrictamente el uso de la configuración de rutas múltiples en entornos SAN, con un valor recomendado de `find_multipaths: no` en el archivo multipath.conf.
+
Uso de una configuración sin rutas múltiples o uso de `find_multipaths: yes` o `find_multipaths: smart` Un valor incorrecto en el archivo multipath.conf provocará fallos de montaje.  Trident ha recomendado el uso de `find_multipaths: no` Desde el lanzamiento del 21.07.



=====
====


== Despliega el operador Trident e instala Trident usando Helm.

Usando el Tridentlink:https://artifacthub.io/packages/helm/netapp-trident/trident-operator["Carta del timón"^] Puedes implementar el operador Trident e instalar Trident en un solo paso.

Revisarlink:../trident-get-started/kubernetes-deploy.html["Descripción general de la instalación"] para asegurarnos de que ha cumplido los requisitos previos de instalación y ha seleccionado la opción de instalación correcta para su entorno.

.Antes de empezar
Además de lalink:../trident-get-started/kubernetes-deploy.html#before-you-deploy["Requisitos previos de despliegue"] Necesitaslink:https://v3.helm.sh/["Helm versión 3"^] .

.Pasos
. Añadir el repositorio Trident Helm:
+
[listing]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. Usar `helm install` y especifique un nombre para su implementación como en el siguiente ejemplo donde `100.2506.0` es la versión de Trident que estás instalando.
+
[listing]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0 --create-namespace --namespace <trident-namespace>
----
+

NOTE: Si ya has creado un espacio de nombres para Trident, `--create-namespace` Este parámetro no creará un espacio de nombres adicional.



Puedes utilizar `helm list` para revisar los detalles de la instalación, como el nombre, el espacio de nombres, el gráfico, el estado, la versión de la aplicación y el número de revisión.



== Pasar datos de configuración durante la instalación

Existen dos maneras de pasar datos de configuración durante la instalación:

[cols="2"]
|===
| Opción | Descripción 


| `--values`(o `-f` )  a| 
Especifique un archivo YAML con anulaciones.  Esto se puede especificar varias veces y el archivo situado más a la derecha tendrá prioridad.



| `--set`  a| 
Especifique las anulaciones en la línea de comandos.

|===
Por ejemplo, para cambiar el valor predeterminado de `debug` , ejecute el siguiente comando donde `100.2506.0` ¿Cuál es la versión de Trident que estás instalando?

[listing]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0  --create-namespace --namespace trident --set tridentDebug=true
----


== Opciones de configuración

Esta tabla y la `values.yaml` El archivo, que forma parte del gráfico de Helm, proporciona la lista de claves y sus valores predeterminados.

[cols="1,2,3"]
|===
| Opción | Descripción | Por defecto 


| `nodeSelector` | Etiquetas de nodo para la asignación de pods |  


| `podAnnotations` | Anotaciones de pods |  


| `deploymentAnnotations` | Anotaciones de despliegue |  


| `tolerations` | Tolerancias para la asignación de pods |  


| `affinity` | Afinidad por la asignación de cápsulas  a| 
[listing]
----
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
              - amd64
            - key: kubernetes.io/os
              operator: In
              values:
              - linux
----

WARNING: No elimine la afinidad predeterminada del archivo values.yaml.  Cuando desee proporcionar una afinidad personalizada, extienda la afinidad predeterminada.



| `tridentControllerPluginNodeSelector` | Selectores de nodos adicionales para pods. Referirse a <<Comprender los pods del controlador y los pods de nodo>> Para más detalles. |  


| `tridentControllerPluginTolerations` | Anula las tolerancias de Kubernetes para los pods. Referirse a <<Comprender los pods del controlador y los pods de nodo>> Para más detalles. |  


| `tridentNodePluginNodeSelector` | Selectores de nodos adicionales para pods. Referirse a <<Comprender los pods del controlador y los pods de nodo>> Para más detalles. |  


| `tridentNodePluginTolerations` | Anula las tolerancias de Kubernetes para los pods. Referirse a <<Comprender los pods del controlador y los pods de nodo>> Para más detalles. |  


| `imageRegistry` | Identifica el registro para el `trident-operator` , `trident` y otras imágenes.  Déjelo vacío para aceptar el valor predeterminado.  IMPORTANTE: Al instalar Trident en un repositorio privado, si está utilizando `imageRegistry` Cambie para especificar la ubicación del repositorio, no utilice `/netapp/` en la ruta del repositorio. | `""` 


| `imagePullPolicy` | Establece la política de extracción de imágenes para el `trident-operator` . | `IfNotPresent` 


| `imagePullSecrets` | Establece los secretos de extracción de imágenes para el `trident-operator` , `trident` y otras imágenes. |  


| `kubeletDir` | Permite anular la ubicación del host del estado interno de kubelet. | `"/var/lib/kubelet"` 


| `operatorLogLevel` | Permite configurar el nivel de registro del operador Trident en: `trace` , `debug` , `info` , `warn` , `error` , o `fatal` . | `"info"` 


| `operatorDebug` | Permite configurar el nivel de registro del operador Trident en modo de depuración. | `true` 


| `operatorImage` | Permite la anulación completa de la imagen para `trident-operator` . | `""` 


| `operatorImageTag` | Permite anular la etiqueta de `trident-operator` imagen. | `""` 


| `tridentIPv6` | Permite que Trident funcione en clústeres IPv6. | `false` 


| `tridentK8sTimeout` | Anula el tiempo de espera predeterminado de 30 segundos para la mayoría de las operaciones de API de Kubernetes (si es distinto de cero, en segundos). | `0` 


| `tridentHttpRequestTimeout` | Anula el tiempo de espera predeterminado de 90 segundos para las solicitudes HTTP, con `0s` siendo una duración infinita para el tiempo de espera.  No se permiten valores negativos. | `"90s"` 


| `tridentSilenceAutosupport` | Permite desactivar los informes periódicos de AutoSupport de Trident . | `false` 


| `tridentAutosupportImageTag` | Permite modificar la etiqueta de la imagen para el contenedor Trident AutoSupport . | `<version>` 


| `tridentAutosupportProxy` | Permite que el contenedor Trident AutoSupport se comunique con el servidor remoto a través de un proxy HTTP. | `""` 


| `tridentLogFormat` | Establece el formato de registro de Trident(`text` o `json` ). | `"text"` 


| `tridentDisableAuditLog` | Deshabilita el registrador de auditoría de Trident . | `true` 


| `tridentLogLevel` | Permite configurar el nivel de registro de Trident en: `trace` , `debug` , `info` , `warn` , `error` , o `fatal` . | `"info"` 


| `tridentDebug` | Permite configurar el nivel de registro de Trident a `debug` . | `false` 


| `tridentLogWorkflows` | Permite habilitar flujos de trabajo específicos de Trident para el registro de seguimiento o la supresión de registros. | `""` 


| `tridentLogLayers` | Permite habilitar capas específicas de Trident para el registro de seguimiento o la supresión de registros. | `""` 


| `tridentImage` | Permite la sustitución completa de la imagen para Trident. | `""` 


| `tridentImageTag` | Permite modificar la etiqueta de la imagen para Trident. | `""` 


| `tridentProbePort` | Permite anular el puerto predeterminado utilizado para las sondas de actividad/disponibilidad de Kubernetes. | `""` 


| `windows` | Permite instalar Trident en un nodo de trabajo de Windows. | `false` 


| `enableForceDetach` | Permite activar la función de desconexión forzada. | `false` 


| `excludePodSecurityPolicy` | Excluye la política de seguridad del pod del operador de la creación. | `false` 


| `cloudProvider` | Empezar a `"Azure"` al usar identidades administradas o una identidad en la nube en un clúster de AKS.  Configúrelo en "AWS" cuando utilice una identidad en la nube en un clúster EKS. | `""` 


| `cloudIdentity` | Establezca la identidad de carga de trabajo ("azure.workload.identity/client-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx") cuando utilice la identidad en la nube en un clúster de AKS.  Establezca el rol de AWS IAM ("'eks.amazonaws.com/role-arn: arn:aws:iam::123456:role/trident-role'") al usar la identidad en la nube en un clúster de EKS. | `""` 


| `iscsiSelfHealingInterval` | El intervalo en el que se activa la autorreparación iSCSI. | `5m0s` 


| `iscsiSelfHealingWaitTime` | Duración tras la cual la autocuración de iSCSI inicia un intento de resolver una sesión obsoleta mediante el cierre de sesión y el posterior inicio de sesión. | `7m0s` 


| `nodePrep` | Permite a Trident preparar los nodos del clúster Kubernetes para administrar volúmenes utilizando el protocolo de almacenamiento de datos especificado. *Actualmente, `iscsi` es el único valor admitido.* NOTA: A partir de OpenShift 4.19, la versión mínima de Trident compatible con esta función es 25.06.1. |  


| `enableConcurrency`  a| 
Permite operaciones simultáneas del controlador Trident para mejorar el rendimiento.


NOTE: *Vista previa técnica*: esta función es experimental en NetApp Trident 25.06 y actualmente admite flujos de trabajo paralelos limitados con el controlador ONTAP-SAN (protocolos iSCSI y FCP).
| FALSO 


| `k8sAPIQPS`  a| 
El límite de consultas por segundo (QPS) utilizado por el controlador mientras se comunica con el servidor de API de Kubernetes. El valor de ráfaga se establece automáticamente en función del valor QPS.
| `100`; opcional 
|===


=== Comprender los pods del controlador y los pods de nodo

Trident se ejecuta como un único pod de controlador, más un pod de nodo en cada nodo de trabajo del clúster.  El pod del nodo debe estar ejecutándose en cualquier host donde se desee potencialmente montar un volumen Trident .

Kuberneteslink:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/["selectores de nodos"^] ylink:https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/["tolerancias y máculas"^] Se utilizan para restringir un pod a ejecutarse en un nodo específico o preferido.  Utilizando el `ControllerPlugin` y `NodePlugin` , puedes especificar restricciones y anulaciones.

* El plugin del controlador gestiona el aprovisionamiento y la administración de volúmenes, como las instantáneas y el cambio de tamaño.
* El plugin del nodo se encarga de conectar el almacenamiento al nodo.

