---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-customize-deploy-tridentctl.html 
keywords: deploy, Trident, methods, operator, tridentctl, helm, attributes, customize 
summary: Puedes utilizar el instalador de Trident para personalizar la implementación. 
---
= Personalizar la instalación de tridentctl
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes utilizar el instalador de Trident para personalizar la instalación.



== Obtén más información sobre el instalador.

El instalador de Trident le permite personalizar los atributos.  Por ejemplo, si ha copiado la imagen de Trident a un repositorio privado, puede especificar el nombre de la imagen mediante el uso de `--trident-image` .  Si ha copiado la imagen de Trident , así como las imágenes auxiliares de CSI necesarias, a un repositorio privado, podría ser preferible especificar la ubicación de dicho repositorio mediante el siguiente comando: `--image-registry` interruptor, que toma la forma `<registry FQDN>[:port]` .


IMPORTANT: Al instalar Trident en un repositorio privado, si está utilizando `--image-registry` Cambie para especificar la ubicación del repositorio, no utilice `/netapp/` en la ruta del repositorio. Por ejemplo: `./tridentctl install --image-registry <image-registry> -n <namespace>`

Si estás utilizando una distribución de Kubernetes, donde `kubelet` Mantiene sus datos en una ruta distinta a la habitual. `/var/lib/kubelet` , puede especificar la ruta alternativa mediante `--kubelet-dir` .

Si necesita personalizar la instalación más allá de lo que permiten los argumentos del instalador, también puede personalizar los archivos de implementación.  Utilizando el `--generate-custom-yaml` El parámetro crea los siguientes archivos YAML en el instalador. `setup` directorio:

* `trident-clusterrolebinding.yaml`
* `trident-deployment.yaml`
* `trident-crds.yaml`
* `trident-clusterrole.yaml`
* `trident-daemonset.yaml`
* `trident-service.yaml`
* `trident-namespace.yaml`
* `trident-serviceaccount.yaml`
* `trident-resourcequota.yaml`


Una vez generados estos archivos, puede modificarlos según sus necesidades y luego utilizarlos. `--use-custom-yaml` para instalar su implementación personalizada.

[source, console]
----
./tridentctl install -n trident --use-custom-yaml
----