---
sidebar: sidebar 
permalink: trident-install/kubernetes-deploy-helm.html 
keywords: deploy, Trident, operator, helm, helm chart, configuration, values, standard, registry 
summary: Puedes desplegar el operador Trident e instalar Trident usando Helm.  Este proceso se aplica a las instalaciones en las que las imĂ¡genes de contenedor requeridas por Trident no estĂ¡n almacenadas en un registro privado. 
---
= Desplegar el operador Trident usando Helm (modo estĂ¡ndar)
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes desplegar el operador Trident e instalar Trident usando Helm.  Este proceso se aplica a las instalaciones en las que las imĂ¡genes de contenedor requeridas por Trident no estĂ¡n almacenadas en un registro privado.  Si dispone de un registro de imĂ¡genes privado, utilice ellink:kubernetes-deploy-helm-mirror.html["proceso para el despliegue sin conexiĂ³n"] .



== InformaciĂ³n crĂ­tica sobre Trident 25.06

*Debe leer la siguiente informaciĂ³n crĂ­tica sobre Trident.*

.<strong>InformaciĂ³n crĂ­tica sobre Trident</strong>
[%collapsible%open]
====
[]
=====
* Kubernetes 1.34 ahora es compatible con Trident. Actualice Trident antes de actualizar Kubernetes.
* Trident impone estrictamente el uso de la configuraciĂ³n de rutas mĂºltiples en entornos SAN, con un valor recomendado de `find_multipaths: no` en el archivo multipath.conf.
+
Uso de una configuraciĂ³n sin rutas mĂºltiples o uso de `find_multipaths: yes` o `find_multipaths: smart` Un valor incorrecto en el archivo multipath.conf provocarĂ¡ fallos de montaje.  Trident ha recomendado el uso de `find_multipaths: no` Desde el lanzamiento del 21.07.



=====
====


== Despliega el operador Trident e instala Trident usando Helm.

Usando el Tridentlink:https://artifacthub.io/packages/helm/netapp-trident/trident-operator["Carta del timĂ³n"^] Puedes implementar el operador Trident e instalar Trident en un solo paso.

Revisa link:../trident-install/kubernetes-deploy.html["DescripciĂ³n general de la instalaciĂ³n"] para asegurarte de que cumpliste los requisitos previos de instalaciĂ³n y seleccionaste la opciĂ³n de instalaciĂ³n correcta para tu entorno.

.Antes de empezar
AdemĂ¡s de link:../trident-install/kubernetes-deploy.html#before-you-deploy["Requisitos previos de despliegue"] tĂº necesitas link:https://v3.helm.sh/["Helm versiĂ³n 3"^].

.Pasos
. AĂ±adir el repositorio Trident Helm:
+
[listing]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. Usar `helm install` y especifique un nombre para su implementaciĂ³n como en el siguiente ejemplo donde `100.2506.0` es la versiĂ³n de Trident que estĂ¡s instalando.
+
[listing]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0 --create-namespace --namespace <trident-namespace>
----
+

NOTE: Si ya has creado un espacio de nombres para Trident, `--create-namespace` Este parĂ¡metro no crearĂ¡ un espacio de nombres adicional.



Puedes utilizar `helm list` para revisar los detalles de la instalaciĂ³n, como el nombre, el espacio de nombres, el grĂ¡fico, el estado, la versiĂ³n de la aplicaciĂ³n y el nĂºmero de revisiĂ³n.



== Pasar datos de configuraciĂ³n durante la instalaciĂ³n

Existen dos maneras de pasar datos de configuraciĂ³n durante la instalaciĂ³n:

[cols="2"]
|===
| OpciĂ³n | DescripciĂ³n 


| `--values`(o `-f` )  a| 
Especifique un archivo YAML con anulaciones.  Esto se puede especificar varias veces y el archivo situado mĂ¡s a la derecha tendrĂ¡ prioridad.



| `--set`  a| 
Especifique las anulaciones en la lĂ­nea de comandos.

|===
Por ejemplo, para cambiar el valor predeterminado de `debug` , ejecute el siguiente comando donde `100.2506.0` Â¿CuĂ¡l es la versiĂ³n de Trident que estĂ¡s instalando?

[listing]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0  --create-namespace --namespace trident --set tridentDebug=true
----


== Opciones de configuraciĂ³n

Esta tabla y la `values.yaml` El archivo, que forma parte del grĂ¡fico de Helm, proporciona la lista de claves y sus valores predeterminados.

[cols="1,2,3"]
|===
| OpciĂ³n | DescripciĂ³n | Por defecto 


| `nodeSelector` | Etiquetas de nodo para la asignaciĂ³n de pods |  


| `podAnnotations` | Anotaciones de pods |  


| `deploymentAnnotations` | Anotaciones de despliegue |  


| `tolerations` | Tolerancias para la asignaciĂ³n de pods |  


| `affinity` | Afinidad por la asignaciĂ³n de cĂ¡psulas  a| 
[listing]
----
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
              - amd64
            - key: kubernetes.io/os
              operator: In
              values:
              - linux
----

WARNING: No elimine la afinidad predeterminada del archivo values.yaml.  Cuando desee proporcionar una afinidad personalizada, extienda la afinidad predeterminada.



| `tridentControllerPluginNodeSelector` | Selectores de nodos adicionales para pods. Referirse a <<Comprender los pods del controlador y los pods de nodo>> Para mĂ¡s detalles. |  


| `tridentControllerPluginTolerations` | Anula las tolerancias de Kubernetes para los pods. Referirse a <<Comprender los pods del controlador y los pods de nodo>> Para mĂ¡s detalles. |  


| `tridentNodePluginNodeSelector` | Selectores de nodos adicionales para pods. Referirse a <<Comprender los pods del controlador y los pods de nodo>> Para mĂ¡s detalles. |  


| `tridentNodePluginTolerations` | Anula las tolerancias de Kubernetes para los pods. Referirse a <<Comprender los pods del controlador y los pods de nodo>> Para mĂ¡s detalles. |  


| `imageRegistry` | Identifica el registro para el `trident-operator` , `trident` y otras imĂ¡genes.  DĂ©jelo vacĂ­o para aceptar el valor predeterminado.  IMPORTANTE: Al instalar Trident en un repositorio privado, si estĂ¡ utilizando `imageRegistry` Cambie para especificar la ubicaciĂ³n del repositorio, no utilice `/netapp/` en la ruta del repositorio. | `""` 


| `imagePullPolicy` | Establece la polĂ­tica de extracciĂ³n de imĂ¡genes para el `trident-operator` . | `IfNotPresent` 


| `imagePullSecrets` | Establece los secretos de extracciĂ³n de imĂ¡genes para el `trident-operator` , `trident` y otras imĂ¡genes. |  


| `kubeletDir` | Permite anular la ubicaciĂ³n del host del estado interno de kubelet. | `"/var/lib/kubelet"` 


| `operatorLogLevel` | Permite configurar el nivel de registro del operador Trident en: `trace` , `debug` , `info` , `warn` , `error` , o `fatal` . | `"info"` 


| `operatorDebug` | Permite configurar el nivel de registro del operador Trident en modo de depuraciĂ³n. | `true` 


| `operatorImage` | Permite la anulaciĂ³n completa de la imagen para `trident-operator` . | `""` 


| `operatorImageTag` | Permite anular la etiqueta de `trident-operator` imagen. | `""` 


| `tridentIPv6` | Permite que Trident funcione en clĂºsteres IPv6. | `false` 


| `tridentK8sTimeout` | Anula el tiempo de espera predeterminado de 30 segundos para la mayorĂ­a de las operaciones de API de Kubernetes (si es distinto de cero, en segundos). | `0` 


| `tridentHttpRequestTimeout` | Anula el tiempo de espera predeterminado de 90 segundos para las solicitudes HTTP, con `0s` siendo una duraciĂ³n infinita para el tiempo de espera.  No se permiten valores negativos. | `"90s"` 


| `tridentSilenceAutosupport` | Permite desactivar los informes periĂ³dicos de AutoSupport de Trident . | `false` 


| `tridentAutosupportImageTag` | Permite modificar la etiqueta de la imagen para el contenedor Trident AutoSupport . | `<version>` 


| `tridentAutosupportProxy` | Permite que el contenedor Trident AutoSupport se comunique con el servidor remoto a travĂ©s de un proxy HTTP. | `""` 


| `tridentLogFormat` | Establece el formato de registro de Trident(`text` o `json` ). | `"text"` 


| `tridentDisableAuditLog` | Deshabilita el registrador de auditorĂ­a de Trident . | `true` 


| `tridentLogLevel` | Permite configurar el nivel de registro de Trident en: `trace` , `debug` , `info` , `warn` , `error` , o `fatal` . | `"info"` 


| `tridentDebug` | Permite configurar el nivel de registro de Trident a `debug` . | `false` 


| `tridentLogWorkflows` | Permite habilitar flujos de trabajo especĂ­ficos de Trident para el registro de seguimiento o la supresiĂ³n de registros. | `""` 


| `tridentLogLayers` | Permite habilitar capas especĂ­ficas de Trident para el registro de seguimiento o la supresiĂ³n de registros. | `""` 


| `tridentImage` | Permite la sustituciĂ³n completa de la imagen para Trident. | `""` 


| `tridentImageTag` | Permite modificar la etiqueta de la imagen para Trident. | `""` 


| `tridentProbePort` | Permite anular el puerto predeterminado utilizado para las sondas de actividad/disponibilidad de Kubernetes. | `""` 


| `windows` | Permite instalar Trident en un nodo de trabajo de Windows. | `false` 


| `enableForceDetach` | Permite activar la funciĂ³n de desconexiĂ³n forzada. | `false` 


| `excludePodSecurityPolicy` | Excluye la polĂ­tica de seguridad del pod del operador de la creaciĂ³n. | `false` 


| `cloudProvider` | Empezar a `"Azure"` al usar identidades administradas o una identidad en la nube en un clĂºster de AKS.  ConfigĂºrelo en "AWS" cuando utilice una identidad en la nube en un clĂºster EKS. | `""` 


| `cloudIdentity` | Establezca la identidad de carga de trabajo ("azure.workload.identity/client-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx") cuando utilice la identidad en la nube en un clĂºster de AKS.  Establezca el rol de AWS IAM ("'eks.amazonaws.com/role-arn: arn:aws:iam::123456:role/trident-role'") al usar la identidad en la nube en un clĂºster de EKS. | `""` 


| `iscsiSelfHealingInterval` | El intervalo en el que se activa la autorreparaciĂ³n iSCSI. | `5m0s` 


| `iscsiSelfHealingWaitTime` | DuraciĂ³n tras la cual la autocuraciĂ³n de iSCSI inicia un intento de resolver una sesiĂ³n obsoleta mediante el cierre de sesiĂ³n y el posterior inicio de sesiĂ³n. | `7m0s` 


| `nodePrep` | Permite a Trident preparar los nodos del clĂºster Kubernetes para administrar volĂºmenes utilizando el protocolo de almacenamiento de datos especificado. *Actualmente, `iscsi` es el Ăºnico valor admitido.* NOTA: A partir de OpenShift 4.19, la versiĂ³n mĂ­nima de Trident compatible con esta funciĂ³n es 25.06.1. |  


| `enableConcurrency`  a| 
Permite operaciones simultĂ¡neas del controlador Trident para mejorar el rendimiento.


NOTE: *Vista previa tĂ©cnica*: esta funciĂ³n es experimental en NetApp Trident 25.06 y actualmente admite flujos de trabajo paralelos limitados con el controlador ONTAP-SAN (protocolos iSCSI y FCP).
| FALSO 


| `k8sAPIQPS`  a| 
El lĂ­mite de consultas por segundo (QPS) utilizado por el controlador mientras se comunica con el servidor de API de Kubernetes. El valor de rĂ¡faga se establece automĂ¡ticamente en funciĂ³n del valor QPS.
| `100`; opcional 
|===


=== Comprender los pods del controlador y los pods de nodo

Trident se ejecuta como un Ăºnico pod de controlador, mĂ¡s un pod de nodo en cada nodo de trabajo del clĂºster.  El pod del nodo debe estar ejecutĂ¡ndose en cualquier host donde se desee potencialmente montar un volumen Trident .

Kuberneteslink:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/["selectores de nodos"^] ylink:https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/["tolerancias y mĂ¡culas"^] Se utilizan para restringir un pod a ejecutarse en un nodo especĂ­fico o preferido.  Utilizando el `ControllerPlugin` y `NodePlugin` , puedes especificar restricciones y anulaciones.

* El plugin del controlador gestiona el aprovisionamiento y la administraciĂ³n de volĂºmenes, como las instantĂ¡neas y el cambio de tamaĂ±o.
* El plugin del nodo se encarga de conectar el almacenamiento al nodo.

