= Anotación de tiempo de espera del movimiento de datos
:allow-uri-read: 




== Anotación de tiempo de espera del movimiento de datos

Durante las operaciones de copia de seguridad y restauración, puede utilizar la anotación `protect.trident.netapp.io/data-mover-timeout-sec` para configurar el tiempo de espera para las operaciones de movimiento de datos.  Esta anotación especifica el tiempo máximo, en segundos, que un agente de transferencia de datos debe esperar a que se complete una operación específica antes de que se agote el tiempo de espera.  Resulta especialmente útil en situaciones donde problemas de red u otros factores podrían causar la interrupción de las operaciones de transferencia de datos.  Ayuda a detectar y gestionar las operaciones atascadas, en lugar de establecer un tiempo de espera general para todo el proceso.  Por ejemplo, si no se logra ningún progreso en la restauración de los datos del volumen debido a problemas de red, la operación caducará según la duración especificada.

Puedes utilizar esta anotación en tu archivo YAML como se muestra a continuación:

[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: BackupRestore
metadata:
  name: bkp-restore-kopia
  namespace: trident-protect
  annotations: # Optional annotations to configure data movement timeout
    protect.trident.netapp.io/data-mover-timeout-sec: "2"
spec:
  appVaultRef: appvault-name
  appArchivePath: my-backup-path
  namespaceMapping: [{"source": "my-source-namespace", "destination": "my-destination-namespace"}]
  storageClassMapping:
    destination: "${destinationStorageClass}"
    source: "${sourceStorageClass}"
----
En este ejemplo, la anotación falla. `BackupRestore` operación si no se produce ningún progreso en 2 segundos en la operación de restauración.


NOTE: Si el valor de la anotación es menor o igual a 0, la operación fallará inmediatamente.
