---
sidebar: sidebar 
permalink: trident-get-started/intro.html 
keywords: product overview, Trident, fsx, element, google cloud, cvs, architecture, node pod, controller pod, pods, csi, sidecar 
summary: 'Trident es un proyecto de código abierto con soporte completo mantenido por NetApp.  Ha sido diseñado para ayudarle a satisfacer las demandas de persistencia de su aplicación en contenedores utilizando interfaces estándar de la industria, como la Interfaz de Almacenamiento de Contenedores (CSI).' 
---
= Aprende sobre Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident es un proyecto de código abierto con soporte completo mantenido por NetApp.  Ha sido diseñado para ayudarle a satisfacer las demandas de persistencia de su aplicación en contenedores utilizando interfaces estándar de la industria, como la Interfaz de Almacenamiento de Contenedores (CSI).



== ¿Qué es Trident?

NetApp Trident permite el consumo y la gestión de recursos de almacenamiento en todas las plataformas de almacenamiento NetApp más populares, tanto en la nube pública como en las instalaciones, incluidos los clústeres ONTAP locales (AFF, FAS y ASA), ONTAP Select, Cloud Volumes ONTAP, el software Element (NetApp HCI, SolidFire), Azure NetApp Files, Amazon FSx for NetApp ONTAP y Cloud Volumes Service en Google Cloud.

Trident es un orquestador de almacenamiento dinámico compatible con la interfaz de almacenamiento de contenedores (CSI) que se integra de forma nativa conlink:https://kubernetes.io/["Kubernetes"^] .  Trident se ejecuta como un único Pod de controlador más un Pod de nodo en cada nodo de trabajo del clúster. Referirse a link:../trident-get-started/architecture.html["Arquitectura Trident"] Para más detalles.

Trident también proporciona integración directa con el ecosistema Docker para las plataformas de almacenamiento NetApp .  El complemento NetApp Docker Volume (nDVP) admite el aprovisionamiento y la gestión de recursos de almacenamiento desde la plataforma de almacenamiento a los hosts de Docker. Referirse a link:../trident-docker/deploy-docker.html["Implementar Trident para Docker"] Para más detalles.


NOTE: Si esta es la primera vez que usa Kubernetes, debería familiarizarse con...link:https://kubernetes.io/docs/home/["Conceptos y herramientas de Kubernetes"^] .



== Integración de Kubernetes con productos NetApp

La cartera de productos de almacenamiento de NetApp se integra con muchos aspectos de un clúster de Kubernetes, proporcionando capacidades avanzadas de gestión de datos que mejoran la funcionalidad, la capacidad, el rendimiento y la disponibilidad de la implementación de Kubernetes.

.Amazon FSx for NetApp ONTAP
[%collapsible]
====
link:https://www.netapp.com/aws/fsx-ontap/["Amazon FSx for NetApp ONTAP"^]Es un servicio de AWS totalmente administrado que le permite lanzar y ejecutar sistemas de archivos basados ​​en el sistema operativo de almacenamiento NetApp ONTAP .

====
.Azure NetApp Files
[%collapsible]
====
https://www.netapp.com/azure/azure-netapp-files/["Azure NetApp Files"^]Es un servicio de compartición de archivos de Azure de nivel empresarial, impulsado por NetApp.  Puede ejecutar sus cargas de trabajo basadas en archivos más exigentes en Azure de forma nativa, con el rendimiento y la rica gestión de datos que espera de NetApp.

====
.Cloud Volumes ONTAP
[%collapsible]
====
link:https://www.netapp.com/cloud-services/cloud-volumes-ontap/["Cloud Volumes ONTAP"^]Es un dispositivo de almacenamiento exclusivamente de software que ejecuta el software de gestión de datos ONTAP en la nube.

====
.Google Cloud NetApp Volumes
[%collapsible]
====
link:https://bluexp.netapp.com/google-cloud-netapp-volumes?utm_source=GitHub&utm_campaign=Trident["Google Cloud NetApp Volumes"^]Es un servicio de almacenamiento de archivos totalmente administrado en Google Cloud que proporciona almacenamiento de archivos de alto rendimiento y nivel empresarial.

====
.Software Element
[%collapsible]
====
https://www.netapp.com/data-management/element-software/["Elemento"^]Permite al administrador de almacenamiento consolidar las cargas de trabajo garantizando el rendimiento y posibilitando una infraestructura de almacenamiento simplificada y optimizada.

====
.HCI de NetApp
[%collapsible]
====
link:https://docs.netapp.com/us-en/hci/docs/concept_hci_product_overview.html["HCI de NetApp"^]Simplifica la gestión y la escalabilidad del centro de datos al automatizar las tareas rutinarias y permitir que los administradores de infraestructura se centren en funciones más importantes.

Trident puede aprovisionar y administrar dispositivos de almacenamiento para aplicaciones en contenedores directamente en la plataforma de almacenamiento NetApp HCI subyacente.

====
.ONTAP de NetApp
[%collapsible]
====
link:https://docs.netapp.com/us-en/ontap/index.html["ONTAP de NetApp"^]es el sistema operativo de almacenamiento unificado y multiprotocolo de NetApp que proporciona capacidades avanzadas de gestión de datos para cualquier aplicación.

Los sistemas ONTAP tienen configuraciones totalmente flash, híbridas o totalmente HDD y ofrecen muchos modelos de implementación diferentes: clústeres FAS, AFA y ASA locales, ONTAP Select y Cloud Volumes ONTAP.  Trident admite estos modelos de implementación de ONTAP .

====